version: 3
# endpoint: ${HASURA_GRAPHQL_ENDPOINT}
endpoint: https://hasura-service-utxnnash3a-an.a.run.app
admin_secret: hasura
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: ${ACTION_BASE_URL}